# Generated by Django 5.1.9 on 2025-06-14 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_status'),
        ('swap', '0002_alter_swaprequest_status_swapmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swaprequest',
            unique_together={('from_trader', 'offered_item', 'requested_item')},
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='from_trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='offered_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_requests', to='item.item'),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='requested_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_in_requests', to='item.item'),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='to_trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SwapMessage',
        ),
        migrations.RemoveField(
            model_name='swaprequest',
            name='message',
        ),
    ]
