# Generated by Django 5.1.9 on 2025-06-10 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/additional/')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='additional_image_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='additional_image_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='additional_image_3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='additional_image_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='Untitled Item', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='trader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
        migrations.AddField(
            model_name='item',
            name='additional_images',
            field=models.ManyToManyField(blank=True, to='item.itemimage'),
        ),
    ]
