# Generated by Django 5.1.9 on 2025-06-10 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_itemimage_remove_item_additional_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='additional_images',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='item.item'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='extras/'),
        ),
    ]
