# Generated by Django 5.1.9 on 2025-06-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_item_additional_images_itemimage_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='preferred_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='featured_image',
            field=models.ImageField(default='items/default.jpg', upload_to='items/'),
        ),
    ]
