# Generated by Django 5.1.9 on 2025-06-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_preferred_item_alter_item_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('swapped', 'Swapped'), ('given', 'Given Away')], default='available', max_length=20),
        ),
    ]
