# Generated by Django 5.1.9 on 2025-07-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_item_featured_image_alter_itemimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
