# Generated by Django 5.1.9 on 2025-07-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_item_expires_at_item_is_archived'),
    ]

    operations = [
    ]
