# Generated by Django 5.1.9 on 2025-07-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_update_archive_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('swapped', 'Swapped'), ('given', 'Given Away'), ('processing', 'Processing')], default='available', max_length=20),
        ),
    ]
