# Generated by Django 5.1.9 on 2025-08-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_remove_item_location_item_city_item_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
