# Generated by Django 5.1.9 on 2025-08-03 23:28

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_item_slug'),
        ('location', '0006_alter_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='location.city'),
        ),
        migrations.AlterField(
            model_name='item',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='location.country'),
        ),
        migrations.AlterField(
            model_name='item',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
