# Generated by Django 5.1.9 on 2025-08-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_alter_item_city_alter_item_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
