# Generated by Django 5.1.9 on 2025-06-07 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='address',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='rating',
        ),
        migrations.AddField(
            model_name='trader',
            name='date_signed_up',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trader',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trader',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
