# Generated by Django 5.1.9 on 2025-06-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_remove_trader_address_remove_trader_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='location',
        ),
        migrations.AddField(
            model_name='trader',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trader',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
