# Generated by Django 5.1.9 on 2025-06-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_remove_trader_location_trader_city_trader_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
