# Generated by Django 5.1.9 on 2025-06-30 15:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_alter_trader_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
