# Generated by Django 5.1.9 on 2025-08-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_city_country_alter_trader_city_city_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='city',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='country',
        ),
        migrations.RemoveField(
            model_name='trader',
            name='postcode',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
