# Generated by Django 5.1.9 on 2025-08-01 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('trader', '0008_city_country_trader_city_city_country_trader_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traders', to='location.city'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traders', to='location.country'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
