# Generated by Django 5.1.9 on 2025-07-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_message', '0001_initial'),
    ]

    operations = [
    ]
