# Generated by Django 5.1.9 on 2025-08-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_city_slug_trader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='trader',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
